In [ ]:
from google.colab import files
uploaded = files.upload()

Saving 1.csv to 1.csv


In [ ]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans

In [ ]:
name=['timestamp','cpu cores','cpu capacity provisioned','cpu usage','cpu usage percent','memory capacity provisioned','memory usage','disk read throughput','disk write throughput','network received throughput','network transmitted throughput']
df=pd.read_csv('1.csv',sep=';\t',names=name)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


In [ ]:
for i in range(0,len(df)):
  temp = df['timestamp'][i]
  temp_str = temp[1:len(temp)]
  temp_num = int(temp_str)
  df['timestamp'][i] = temp_num


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


In [ ]:
for i in range(0,len(df)):
  temp = df['network transmitted throughput'][i]
  temp_str = temp[0:len(temp)-1]
  temp_num = float(temp_str)
  df['network transmitted throughput'][i] = temp_num


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


In [ ]:
dataset=df.to_numpy()

In [ ]:
X=[]
y=[]
pivot = 0.8*len(dataset)
for i in range(0,len(dataset)):
  if i<pivot:
    X.append(dataset[i])
  else:
    y.append(dataset[i])

In [ ]:
kmeans=KMeans(n_clusters=4, random_state=0).fit(X)
label=kmeans.labels_

print(label)

[3 3 3 ... 2 2 2]


In [ ]:
predicted=kmeans.predict(y)
print(predicted)

[2 2 2 ... 2 2 2]


In [ ]:
print("Four Different Centroids")
kmeans.cluster_centers_

Four Different Centroids


array([[1.37685339e+09, 4.00000000e+00, 1.17039982e+04, 9.37467375e+01,
        8.00980447e-01, 6.71088640e+07, 4.02176835e+04, 1.56925802e+00,
        5.78706080e+00, 1.68793160e+00, 1.09616469e+00],
       [1.37677187e+09, 4.00000000e+00, 1.17039982e+04, 9.24974147e+03,
        7.90306122e+01, 6.71088640e+07, 1.78536949e+07, 5.67074830e+00,
        7.89819728e+03, 2.92156463e+02, 3.52231293e+01],
       [1.37787052e+09, 4.00000000e+00, 1.17039982e+04, 9.22345937e+01,
        7.88060557e-01, 6.71088640e+07, 3.80828454e+04, 1.61773302e+00,
        7.60023287e+00, 2.51828876e+00, 1.09710160e+00],
       [1.37696804e+09, 4.00000000e+00, 1.17039982e+04, 9.91339957e+03,
        8.47009660e+01, 6.71088640e+07, 7.79712075e+06, 3.26955504e+00,
        1.06102693e+04, 5.83808743e+01, 2.94918813e+01]])

In [ ]:
data_points = {}
for i in range(kmeans.n_clusters):
  temp = np.where(kmeans.labels_ == i)
  arr = temp[0]
  cluster=[]
  
  for j in range(0, len(arr)):
    cluster.append( X[arr[j]])
  data_points[i] = cluster

In [ ]:
print(data_points[1])

[array([1376315746, 4, 11703.99824, 10539.450415120002, 90.05, 67108864.0,
       18790479.466666665, 5.466666666666668, 8791.8, 349.66666666666674,
       5.466666666666667], dtype=object), array([1376317246, 4, 11703.99824, 10477.029091173334, 89.51666666666668,
       67108864.0, 20937962.933333334, 0.0, 1.4, 235.53333333333333,
       3.8666666666666667], dtype=object), array([1376398853, 4, 11703.99824, 10531.647749626667, 89.98333333333332,
       67108864.0, 22951228.53333333, 0.0, 4710.466666666666, 642.8,
       7.666666666666667], dtype=object), array([1376399153, 4, 11703.99824, 11056.377004053333, 94.46666666666664,
       67108864.0, 14450773.6, 0.06666666666666668, 8199.0, 0.0,
       1.5333333333333334], dtype=object), array([1376400053, 4, 11703.99824, 10129.81047672, 86.55, 67108864.0,
       14629730.133333333, 2.533333333333333, 10979.8, 716.9333333333333,
       11.066666666666666], dtype=object), array([1376400353, 4, 11703.99824, 11042.72233944, 94.35, 67108864.0,